# Config file for automatic testing at travis-ci.org
jobs:
  include:
    - stage: cli
      language: python
      python:
        - '3.6'
        - '2.7'
      install: pip install -U tox-travis
      script: tox
      # Assuming you have installed the travis-ci CLI tool, after you
      # create the Github repo and add it to Travis, run the
      # following command to finish PyPI deployment setup:
      # $ travis encrypt --add deploy.password
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: mozilla-infosec
        password:
          secure: PLEASE_REPLACE_ME
        on:
          tags: true
          repo: mozilla-iam/federated_aws_cli
          python: 3.6
    - stage: lambda
      language: python
      python: '3.6'
      install: pip install -U tox-travis
      before_script: cd cloudformation/functions
      script: tox

